[workspace]
members = [
    "rkyv",
    "rkyv_bench",
    "rkyv_derive",
    "rkyv_dyn",
    "rkyv_dyn_derive",
    "rkyv_dyn_test",
    "rkyv_test",
    "rkyv_typename",
    "rkyv_typename_derive",
]
