[workspace]
members = [
    "examples/as_string",
    "examples/backwards_compat",
    "examples/json",
    "examples/opcode",
    "rkyv",
    "rkyv_derive",
    "rkyv_dyn",
    "rkyv_dyn_derive",
    "rkyv_dyn_test",
    "rkyv_test",
    "rkyv_typename",
    "rkyv_typename_derive",
]
default-members = [
    "rkyv",
    "rkyv_dyn",
    "rkyv_dyn_test",
    "rkyv_test",
    "rkyv_typename",
]

[workspace.package]
# TODO: STOP!! GO RESOLVE ALL OF THE TODO COMMENTS BEFORE BUMPING THIS VERSION!!
version = "0.8.0"
authors = ["David Koloski <djkoloski@gmail.com>"]
edition = "2021"
license = "MIT"
documentation = "https://docs.rs/rkyv"
repository = "https://github.com/rkyv/rkyv"

[workspace.dependencies]
bytecheck = { version = "0.8", default-features = false, features = ["simdutf8"], path = "../bytecheck/bytecheck" }
hashbrown = "0.12"
proc-macro2 = "1.0"
ptr_meta = { version = "0.3", default-features = false, path = "../ptr_meta/ptr_meta" }
quote = "1.0"
rend = { version = "0.5", default-features = false, path = "../rend" }
rancor = { version = "0.1", deafult-features = false, path = "../rancor" }
rkyv = { version = "=0.8.0", path = "rkyv" }
rkyv_derive = { version = "=0.8.0", path = "rkyv_derive" }
seahash = "4.0"
syn = "1.0"
wasm-bindgen-test = "0.3"
