[package]
name = "rkyv_bench"
version = "0.3.0"
authors = ["David Koloski <djkoloski@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
bincode = "1.3"
bytecheck = { path = "../../bytecheck/bytecheck", version = "0.3" }
criterion = "0.3"
rand = "0.8"
rand_pcg = "0.3"
rkyv = { version = "0.3.0", path = "../rkyv", features = ["validation"] }
rkyv_derive = { version = "0.3.0", path = "../rkyv_derive" }
serde = { version = "1.0", features = ["derive"] }

[[bench]]
name = "bench"
harness = false
