[package]
name = "rkyv"
version = "0.1.0"
authors = ["David Koloski <djkoloski@gmail.com>"]
edition = "2018"
description = "Zero-copy deserialization framework for Rust"
license = "MIT"
documentation = "https://docs.rs/rkyv"
repository = "https://github.com/djkoloski/rkyv"
keywords = ["archive", "rkyv", "serialization", "zero-copy", "no_std"]
categories = ["encoding", "no-std"]
readme = "crates-io.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = { version = "0.5", optional = true }
cfg-if = { version = "1.0", optional = true }
memoffset = "0.6"
rkyv_derive = { version = "=0.1.0", path = "../rkyv_derive" }

[dev-dependencies]
rkyv_derive = { version = "0.1", path = "../rkyv_derive" }

[features]
default = ["std", "inline_more"]
const_generics = []
inline_more = []
more_portable = []
nightly = []
specialization = []
std = ["ahash", "cfg-if"]
