[package]
name = "rkyv"
version = "0.3.0"
authors = ["David Koloski <djkoloski@gmail.com>"]
edition = "2018"
description = "Zero-copy deserialization framework for Rust"
license = "MIT"
documentation = "https://docs.rs/rkyv"
repository = "https://github.com/djkoloski/rkyv"
keywords = ["archive", "rkyv", "serialization", "zero-copy", "no_std"]
categories = ["encoding", "no-std"]
readme = "crates-io.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytecheck = { path = "../../bytecheck/bytecheck", version = "0.3", optional = true }
memoffset = "0.6"
ptr_meta = { path = "../../ptr_meta/ptr_meta", version = "0.1" }
rkyv_derive = { version = "=0.3.0", path = "../rkyv_derive" }
seahash = { version = "4.0", optional = true }

[features]
default = ["std"]
const_generics = []
long_rel_ptrs = []
std = ["seahash"]
strict = ["rkyv_derive/strict"]
validation = ["bytecheck", "std"]

[package.metadata.docs.rs]
features = ["validation"]
