[package]
name = "rkyv"
version = "0.2.0"
authors = ["David Koloski <djkoloski@gmail.com>"]
edition = "2018"
description = "Zero-copy deserialization framework for Rust"
license = "MIT"
documentation = "https://docs.rs/rkyv"
repository = "https://github.com/djkoloski/rkyv"
keywords = ["archive", "rkyv", "serialization", "zero-copy", "no_std"]
categories = ["encoding", "no-std"]
readme = "crates-io.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytecheck = { version = "0.2", optional = true, path = "../../bytecheck/bytecheck" }
cfg-if = { version = "1.0", optional = true }
memoffset = "0.6"
rkyv_derive = { version = "=0.2.0", path = "../rkyv_derive" }
seahash = { version = "4.0", optional = true }

[dev-dependencies]
rkyv_derive = { version = "0.2", path = "../rkyv_derive" }

[features]
default = ["inline_more", "std"]
const_generics = []
inline_more = []
long_rel_ptrs = []
more_portable = []
nightly = []
specialization = []
std = ["seahash", "cfg-if"]
strict = ["rkyv_derive/strict"]
validation = ["bytecheck", "std"]

[package.metadata.docs.rs]
all-features = true
