[package]
name = "rkyv"
version = "0.6.7"
authors = ["David Koloski <djkoloski@gmail.com>"]
edition = "2018"
description = "Zero-copy deserialization framework for Rust"
license = "MIT"
documentation = "https://docs.rs/rkyv"
repository = "https://github.com/djkoloski/rkyv"
keywords = ["archive", "rkyv", "serialization", "zero-copy", "no_std"]
categories = ["encoding", "no-std"]
readme = "crates-io.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytecheck = { git = "https://github.com/djkoloski/bytecheck.git", optional = true, default-features = false }
hashbrown = { version = "0.11", optional = true }
ptr_meta = { version = "~0.1.3", default-features = false }
rend = { version = "~0.2.3", optional = true, default-features = false }
rkyv_derive = { version = "=0.6.7", path = "../rkyv_derive" }
seahash = "4.0"

[features]
default = ["size_32", "std"]
alloc = ["hashbrown"]
arbitrary_enum_discriminant = ["rkyv_derive/arbitrary_enum_discriminant"]
archive_be = ["rend", "rkyv_derive/archive_be"]
archive_le = ["rend", "rkyv_derive/archive_le"]
copy = ["rkyv_derive/copy"]
copy_unsafe = []
size_16 = []
size_32 = []
size_64 = []
std = ["alloc", "bytecheck/std", "rend/std", "ptr_meta/std"]
strict = ["rkyv_derive/strict"]
validation = ["alloc", "bytecheck", "rend/validation"]

[package.metadata.docs.rs]
features = ["validation"]
