[package]
name = "rkyv"
version = "0.6.4"
authors = ["David Koloski <djkoloski@gmail.com>"]
edition = "2018"
description = "Zero-copy deserialization framework for Rust"
license = "MIT"
documentation = "https://docs.rs/rkyv"
repository = "https://github.com/djkoloski/rkyv"
keywords = ["archive", "rkyv", "serialization", "zero-copy", "no_std"]
categories = ["encoding", "no-std"]
readme = "crates-io.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytecheck = { version = "0.5", optional = true }
ptr_meta = { version = "0.1" }
rend = { version = "~0.1.1", optional = true, default-features = false }
rkyv_derive = { version = "=0.6.3", path = "../rkyv_derive" }
seahash = { version = "4.0", optional = true }

[features]
default = ["std"]
arbitrary_enum_discriminant = ["rkyv_derive/arbitrary_enum_discriminant"]
archive_be = ["rend", "rkyv_derive/archive_be"]
archive_le = ["rend", "rkyv_derive/archive_le"]
copy = ["rkyv_derive/copy"]
copy_unsafe = []
size_64 = []
std = ["bytecheck/std", "seahash", "rend/std"]
strict = ["rkyv_derive/strict"]
validation = ["bytecheck", "rend/validation"]

[package.metadata.docs.rs]
features = ["validation"]
