[package]
name = "rkyv_test"
version = "0.0.0"
authors = ["David Koloski <djkoloski@gmail.com>"]
edition = "2018"
description = "Test suite for rkyv crates"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
rkyv = { version = "0.0", path = "../rkyv" }
rkyv_dyn = { version = "0.0", path = "../rkyv_dyn" }
rkyv_typename = { version = "0.0", path = "../rkyv_typename" }

[features]
default = ["std", "inline_more"]
const_generics = ["rkyv/const_generics", "rkyv_typename/const_generics"]
inline_more = ["rkyv/inline_more"]
more_portable = ["rkyv/more_portable"]
nightly = ["rkyv/nightly", "rkyv_dyn/nightly"]
specialization = ["rkyv/specialization"]
std = ["rkyv/std", "rkyv_typename/std"]
vtable_cache = ["rkyv_dyn/vtable_cache"]
