[package]
name = "rkyv_test"
version = "0.2.1"
authors = ["David Koloski <djkoloski@gmail.com>"]
edition = "2018"
description = "Test suite for rkyv crates"
license = "MIT"
repository = "https://github.com/djkoloski/rkyv"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytecheck = { version = "0.3.0", optional = true }
rkyv = { path = "../rkyv", default-features = false }
rkyv_dyn = { path = "../rkyv_dyn" }
rkyv_typename = { path = "../rkyv_typename" }

[features]
default = ["validation"]
const_generics = ["rkyv/const_generics", "rkyv_typename/const_generics"]
long_rel_ptrs = ["rkyv/long_rel_ptrs"]
nightly = ["rkyv_dyn/nightly"]
std = ["rkyv/std", "rkyv_typename/std"]
strict = ["rkyv/strict"]
validation = ["bytecheck", "std", "rkyv/validation"]
vtable_cache = ["rkyv_dyn/vtable_cache"]
