[package]
name = "rkyv_test"
version = "0.1.1"
authors = ["David Koloski <djkoloski@gmail.com>"]
edition = "2018"
description = "Test suite for rkyv crates"
license = "MIT"
repository = "https://github.com/djkoloski/rkyv"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytecheck = { version = "0.1", path = "../../bytecheck/bytecheck", default-features = false, optional = true }
rkyv = { version = "0.1.1", path = "../rkyv", default-features = false }
rkyv_dyn = { version = "0.1.1", path = "../rkyv_dyn" }
rkyv_typename = { version = "0.1.1", path = "../rkyv_typename" }

[features]
default = ["inline_more", "validation"]
const_generics = ["rkyv/const_generics", "rkyv_typename/const_generics"]
inline_more = ["rkyv/inline_more"]
long_rel_ptrs = ["rkyv/long_rel_ptrs"]
more_portable = ["rkyv/more_portable"]
nightly = ["rkyv/nightly", "rkyv_dyn/nightly"]
specialization = ["rkyv/specialization"]
std = ["rkyv/std", "rkyv_typename/std"]
validation = ["std", "bytecheck", "rkyv/validation"]
vtable_cache = ["rkyv_dyn/vtable_cache"]
