[package]
name = "rkyv_dyn"
version = "0.0.0"
authors = ["David Koloski <djkoloski@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rkyv = { version = "0.0", path = "../rkyv" }
rkyv_dyn_derive = { version = "=0.0.0", path = "../rkyv_dyn_derive" }
lazy_static = "1.4"
inventory = "0.1"
rkyv_typename = { version = "0.0", path = "../rkyv_typename" }

[dev-dependencies]
rkyv_dyn_derive = { version = "0.0", path = "../rkyv_dyn_derive" }

[features]
default = []
vtable_cache = []
nightly = ["rkyv/nightly"]
