[package]
name = "rkyv_typename"
version = "0.1.0"
authors = ["David Koloski <djkoloski@gmail.com>"]
edition = "2018"
description = "Customizable naming for types"
license = "MIT"
documentation = "https://docs.rs/rkyv_typename"
repository = "https://github.com/djkoloski/rkyv"
keywords = ["archive", "rkyv", "serialization", "zero-copy", "no_std"]
categories = ["encoding", "no-std"]
readme = "crates-io.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rkyv_typename_derive = { version = "=0.1.0", path = "../rkyv_typename_derive" }

[dev-dependencies]
rkyv_typename_derive = { version = "0.1", path = "../rkyv_typename_derive" }

[features]
default = ["std"]
const_generics = []
std = []
